Unary minus
aslanovr/MyCalc pull request #1
Opened 2018-11-02 13:30 UTC by aslanovr

2018-11-02 14:30 UTC, zor07 requested changes

2018-11-02 14:30 UTC, zor07 commented on src/main/java/ru/rasl/CalcLogic.java
> +                if (priority > 1) {
Не понятно что за приоритет такой. И что ты этим проверяешь. Опять же, если все приоритеты хранить как 10,20,30 и тд эта штука всегда будет true...

2018-11-02 14:30 UTC, zor07 commented on src/main/java/ru/rasl/CalcLogic.java
> +                    while (standardOperators.get(stackOperations.peek()) != 1) {
Вот опять единица, это называется магическая константа, надо убрать все цифры из всех условий

2018-11-02 14:30 UTC, zor07 commented on src/main/java/ru/rasl/CalcLogic.java
> +            if (standardOperators.containsKey(rpn.get(i)) && standardOperators.get(rpn.get(i)) > 1) {
Тоже самое

2018-11-02 14:30 UTC, zor07 commented on src/main/java/ru/rasl/CalcLogic.java
> +            if (standardOperators.containsKey(rpn.get(i)) && standardOperators.get(rpn.get(i)) > 1) {
```
int bracketPriority = standardOperators.get("(");
if (currentPriority > bracketPriority) {...}

```
Вот так хотя бы

2018-11-02 14:30 UTC, zor07 commented on src/test/java/ru/rasl/CalcLogicTest.java
> +public class CalcLogicTest {
Где тесты, Лебовский?

2018-11-02 14:30 UTC, zor07 commented on src/test/java/ru/rasl/CalcLogicTest.java
> +    public void infixToRPNTest() {
Данный тест покрывает очень мало кейсов

2018-11-02 14:30 UTC, zor07 commented on .idea/libraries/Arquillian_JUnit_Release.xml
> +<component name="libraryTable">
Все ненужное должно быть в гитигноре. По крайней мере на будущее это замечание

2018-11-04 14:53 UTC, aslanovr commented on src/main/java/ru/rasl/CalcLogic.java
> +                    while (standardOperators.get(stackOperations.peek()) != 1) {
убрал магическое число

2018-11-04 14:53 UTC, aslanovr commented on src/main/java/ru/rasl/CalcLogic.java
> +            if (standardOperators.containsKey(rpn.get(i)) && standardOperators.get(rpn.get(i)) > 1) {
убрал магическое число

2018-11-04 14:54 UTC, aslanovr commented on .idea/libraries/Arquillian_JUnit_Release.xml
> +<component name="libraryTable">
.gitignor добавил

2018-11-04 14:54 UTC, aslanovr commented on src/main/java/ru/rasl/CalcLogic.java
> +                if (priority > 1) {
убрал магическое число

2018-11-19 17:52 UTC, aslanovr commented on src/test/java/ru/rasl/CalcLogicTest.java
> +public class CalcLogicTest {
Добавил тесты

2018-12-16 14:20 UTC, merged